server.port=8080
spring.jersey.type=filter
spring.jersey.application-path=/api
logging.level.root=WARN
logging.level.org.springframework=WARN
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=user-tsi
spring.rabbitmq.listener.simple.default-requeue-rejected=false
logging.level.org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler=ERROR
spring.data.mongodb.uri=mongodb://localhost:27017/trabalho?replicaSet=rs0
